// English->French Pokemon name lookup, for names coming from a source
// outside the bundled encounter data (e.g. the Altering Cave rotation
// sheet, which only gives English names). Keyed by lowercase English name,
// generated by scripts/extract-data.py from pokemmo-hub's own translations.
let fetchPromise: Promise<Record<string, string>> | null = null

function fetchNames() {
  if (!fetchPromise) {
    fetchPromise = $fetch<Record<string, string>>('/data/pokemon-names-fr.json')
  }
  return fetchPromise
}

export function usePokemonNamesFr() {
  const names = useState<Record<string, string> | null>('pokemon-names-fr', () => null)

  onMounted(async () => {
    if (!names.value) names.value = await fetchNames()
  })

  function translate(englishName: string) {
    return names.value?.[englishName.toLowerCase()] ?? englishName
  }

  return { translate }
}
